/**
 * Print-ready PDFs built with pdfmake, entirely in the browser.
 * Each builder returns a pdfmake document definition; `renderPdf` turns it into bytes.
 */
import type { Content, TableCell, TDocumentDefinitions } from 'pdfmake/interfaces'
import { fmt } from '../format'
import type { ReportKind } from './catalog'
import { PALETTE } from '../palette'
import type { PlanView, RoomView } from '../planView'
import { attendance, doorList, floorText, masterList, reportHeader, seatingChart, summary } from './reports'

const GREY = '#64748b'
const LINE = '#cbd5e1'
const TEAL = '#0f766e'

function header(view: PlanView, heading: string, sub?: string): Content {
  const h = reportHeader(view)
  return {
    stack: [
      {
        columns: [
          { text: h.title, style: 'kicker' },
          { text: 'SeatWise', alignment: 'right', style: 'kicker', color: TEAL },
        ],
      },
      { text: heading, style: 'h1' },
      { text: [h.session, '  ·  ', h.rule, sub ? `  ·  ${sub}` : ''].join(''), style: 'meta' },
    ],
    margin: [0, 0, 0, 10],
  }
}

const styles: TDocumentDefinitions['styles'] = {
  kicker: { fontSize: 8, color: GREY, bold: true, characterSpacing: 0.5 },
  h1: { fontSize: 18, bold: true, margin: [0, 2, 0, 2] },
  meta: { fontSize: 9, color: GREY },
  th: { bold: true, fontSize: 9, fillColor: '#f1f5f9' },
  small: { fontSize: 8, color: GREY },
}

const tableLayout = {
  hLineColor: () => LINE,
  vLineColor: () => LINE,
  hLineWidth: () => 0.5,
  vLineWidth: () => 0.5,
  paddingTop: () => 3,
  paddingBottom: () => 3,
}

function footer(view: PlanView) {
  return (page: number, pages: number): Content => ({
    columns: [
      { text: `Generated by SeatWise in the browser · ${new Date(view.plan.createdAt).toLocaleString('en-IN')}`, style: 'small' },
      { text: `Page ${page} of ${pages}`, alignment: 'right', style: 'small' },
    ],
    margin: [30, 8, 30, 0],
  })
}

function base(view: PlanView, content: Content[], landscape = false): TDocumentDefinitions {
  return {
    pageSize: 'A4',
    pageOrientation: landscape ? 'landscape' : 'portrait',
    pageMargins: [30, 30, 30, 36],
    content,
    styles,
    defaultStyle: { fontSize: 9 },
    footer: footer(view),
    info: { title: `SeatWise — ${reportHeader(view).title}`, creator: 'SeatWise' },
  }
}

const pageBreak = (i: number): { pageBreak?: 'before' } => (i > 0 ? { pageBreak: 'before' } : {})

// 1. Room seating charts ------------------------------------------------------

function chartTable(view: PlanView, room: RoomView): Content {
  const cells = seatingChart(room)
  const bench = room.room.seatsPerBench ?? 1
  const cols = room.room.cols
  const gaps = bench > 1 ? Math.ceil(cols / bench) - 1 : 0
  const usableWidth = 842 - 60
  // Each table column also takes 8pt of padding (4 + 4) and a 0.5pt border.
  const cellW = Math.min(70, (usableWidth - gaps * (4 + 8.5)) / cols - 8.5)
  const scale = Math.max(0.6, Math.min(1, cellW / 60))
  const widths: number[] = []
  for (let c = 0; c < cols; c++) {
    widths.push(cellW)
    if (bench > 1 && (c + 1) % bench === 0 && c < cols - 1) widths.push(4)
  }
  const body: TableCell[][] = cells.map((row) => {
    const out: TableCell[] = []
    row.forEach((cell, c) => {
      if (cell.kind === 'student') {
        const colour = PALETTE[(view.paperColour.get(cell.paper) ?? 0) % PALETTE.length]
        out.push({
          stack: [
            { text: cell.label, fontSize: 6 * scale, color: GREY },
            { text: cell.paper, fontSize: 7 * scale, alignment: 'center' },
            { text: cell.roll + (cell.special ? ' *' : ''), fontSize: 8.5 * scale, bold: true, alignment: 'center' },
          ],
          fillColor: colour.light,
        })
      } else if (cell.kind === 'blocked') {
        out.push({ stack: [{ text: cell.label, fontSize: 6 * scale, color: GREY }, { text: 'blocked', fontSize: 7 * scale, alignment: 'center', color: GREY }], fillColor: '#e2e8f0' })
      } else {
        out.push({ stack: [{ text: cell.label, fontSize: 6 * scale, color: GREY }, { text: 'empty', fontSize: 7 * scale, alignment: 'center', color: '#94a3b8' }] })
      }
      if (bench > 1 && (c + 1) % bench === 0 && c < cols - 1) out.push({ text: '', border: [false, false, false, false] })
    })
    return out
  })
  return { table: { widths, body, dontBreakRows: true }, layout: { ...tableLayout, paddingTop: () => 2, paddingBottom: () => 2 } }
}

export function seatingChartsDoc(view: PlanView): TDocumentDefinitions {
  const content: Content[] = view.rooms.map((room, i) => {
    const special = [...room.bySeat.values()].some((s) => s.specialNeeds)
    return {
      ...pageBreak(i),
      stack: [
        header(view, `Room ${room.room.name} — seating chart`, [floorText(room.room.floor), `${room.used} students`].filter(Boolean).join(' · ')),
        {
          table: { widths: ['*'], body: [[{ text: 'FRONT  ·  BOARD', alignment: 'center', bold: true, fontSize: 8, color: 'white', fillColor: '#334155' }]] },
          layout: 'noBorders',
          margin: [0, 0, 0, 6],
        },
        chartTable(view, room),
        { text: 'BACK', alignment: 'center', fontSize: 7, color: GREY, margin: [0, 4, 0, 8] },
        {
          table: {
            widths: [10, 45, '*', 30, 'auto'],
            body: [
              [{ text: '' }, { text: 'Paper', style: 'th' }, { text: 'Roll numbers', style: 'th' }, { text: 'Count', style: 'th' }, { text: 'Name', style: 'th' }],
              ...room.papers.map((p) => [
                { text: '', fillColor: PALETTE[(view.paperColour.get(p.paper) ?? 0) % PALETTE.length].light },
                { text: p.paper, bold: true },
                { text: p.ranges.join(', '), fontSize: 8 },
                { text: String(p.count), alignment: 'right' as const },
                { text: p.paperName ?? '', fontSize: 8 },
              ]),
            ],
          },
          layout: tableLayout,
        },
        ...(special ? [{ text: '* special-needs student', style: 'small', margin: [0, 4, 0, 0] } as Content] : []),
      ],
    } as Content
  })
  return base(view, content, true)
}

// 2. Door lists ----------------------------------------------------------------

export function doorListsDoc(view: PlanView): TDocumentDefinitions {
  const h = reportHeader(view)
  const content: Content[] = view.rooms.map((room, i) => ({
    ...pageBreak(i),
    stack: [
      { text: h.title, style: 'kicker' },
      { text: `ROOM ${room.room.name}`, fontSize: 40, bold: true, margin: [0, 8, 0, 0] },
      { text: [h.session, floorText(room.room.floor)].filter(Boolean).join('  ·  '), fontSize: 13, color: GREY, margin: [0, 0, 0, 18] },
      {
        table: {
          headerRows: 1,
          widths: [70, '*', 50],
          body: [
            [{ text: 'Paper', style: 'th', fontSize: 12 }, { text: 'Roll numbers', style: 'th', fontSize: 12 }, { text: 'Count', style: 'th', fontSize: 12, alignment: 'right' }],
            ...doorList(room).map((d) => [
              { stack: [{ text: d.paper, bold: true, fontSize: 14 }, { text: d.paperName, fontSize: 8, color: GREY }] },
              { text: d.rolls, fontSize: 12 },
              { text: String(d.count), fontSize: 14, alignment: 'right' as const },
            ]),
            [{ text: 'Total', bold: true, fontSize: 13 }, { text: '' }, { text: String(room.used), bold: true, fontSize: 14, alignment: 'right' }],
          ],
        },
        layout: { ...tableLayout, paddingTop: () => 7, paddingBottom: () => 7 },
      },
      { text: 'Please check your seat number on the seating chart inside the room.', fontSize: 10, color: GREY, margin: [0, 16, 0, 0] },
    ],
  }))
  return base(view, content)
}

// 3. Master list ----------------------------------------------------------------

export function masterListDoc(view: PlanView): TDocumentDefinitions {
  const rows = masterList(view)
  return base(view, [
    header(view, 'Master list — all students by roll number', `${fmt(rows.length)} students`),
    {
      table: {
        headerRows: 1,
        widths: [60, '*', 70, 45, 45, 30, 70],
        body: [
          ['Roll no.', 'Name', 'Course', 'Paper', 'Room', 'Seat', 'Notes'].map((t) => ({ text: t, style: 'th' })),
          ...rows.map((r) => [r.roll, r.name, r.course, r.paper, { text: r.room, bold: true }, { text: r.seat, bold: true }, { text: r.specialNeeds, fontSize: 7 }]),
        ],
      },
      layout: { ...tableLayout, paddingTop: () => 1.5, paddingBottom: () => 1.5, fillColor: (i: number) => (i > 0 && i % 2 === 0 ? '#f8fafc' : null) },
    },
  ])
}

// 4. Attendance sheets ------------------------------------------------------------

export function attendanceDoc(view: PlanView): TDocumentDefinitions {
  const content: Content[] = view.rooms.map((room, i) => ({
    ...pageBreak(i),
    stack: [
      header(view, `Attendance sheet — Room ${room.room.name}`, `${room.used} students`),
      {
        table: {
          headerRows: 1,
          widths: [28, 60, '*', 45, 80, 90],
          body: [
            ['Seat', 'Roll no.', 'Name', 'Paper', 'Answer sheet no.', 'Signature'].map((t) => ({ text: t, style: 'th' })),
            ...attendance(room).map((r) => [r.seat, { text: r.roll, bold: true }, r.name, r.paper, '', '']),
          ],
          dontBreakRows: true,
        },
        layout: { ...tableLayout, paddingTop: () => 6, paddingBottom: () => 6 },
      },
      {
        columns: [
          { text: 'Present: ________      Absent: ________', margin: [0, 18, 0, 0] },
          { text: 'Invigilator name & signature: ____________________', alignment: 'right', margin: [0, 18, 0, 0] },
        ],
      },
    ],
  }))
  return base(view, content)
}

// 5. Summary ------------------------------------------------------------------------

export function summaryDoc(view: PlanView): TDocumentDefinitions {
  const s = summary(view)
  return base(view, [
    header(view, 'Seating plan summary'),
    { table: { widths: [150, '*'], body: s.items.map(([k, v]) => [{ text: k, bold: true }, v]) }, layout: tableLayout, margin: [0, 0, 0, 14] },
    { text: 'Rooms', bold: true, fontSize: 12, margin: [0, 0, 0, 6] },
    {
      table: {
        headerRows: 1,
        widths: [50, 60, '*', 45, 35, 40],
        body: [
          ['Room', 'Floor', 'Papers', 'Students', 'Empty', 'Usable'].map((t) => ({ text: t, style: 'th' })),
          ...s.rooms.map((r) => [{ text: r.room, bold: true }, r.floor, { text: r.papers, fontSize: 8 }, String(r.students), String(r.empty), String(r.usable)]),
        ],
      },
      layout: tableLayout,
    },
    {
      text: 'Privacy: this plan was generated inside a web browser. No student data was uploaded to any server.',
      style: 'small',
      margin: [0, 14, 0, 0],
    },
  ])
}

export const PDF_BUILDERS: Record<ReportKind, (v: PlanView) => TDocumentDefinitions> = {
  'seating-charts': seatingChartsDoc,
  'door-lists': doorListsDoc,
  'master-list': masterListDoc,
  'attendance-sheets': attendanceDoc,
  summary: summaryDoc,
}

/** Renders a document definition to PDF bytes (pdfmake + bundled Roboto font, loaded lazily). */
export async function renderPdf(doc: TDocumentDefinitions): Promise<Uint8Array> {
  const [{ default: pdfMake }, { default: vfs }] = await Promise.all([import('pdfmake/build/pdfmake'), import('pdfmake/build/vfs_fonts')])
  pdfMake.addVirtualFileSystem(vfs)
  const buffer = await pdfMake.createPdf(doc).getBuffer()
  return new Uint8Array(buffer)
}

/** Loads pdfmake and its fonts ahead of time so downloads also work offline later. */
export async function preloadPdf(): Promise<void> {
  await Promise.all([import('pdfmake/build/pdfmake'), import('pdfmake/build/vfs_fonts')])
}
